/* 
 *
 * 	uib, www.uib.de, 2008-2009
 * 
 *	author Rupert Röder 
 *
 */
 
package de.uib.utilities.table.updates;

import java.util.*;
import javax.swing.table.*;

public class SqlTableInsertItem extends SqlTableEditItem
{
	public SqlTableInsertItem(
		String tableName, 
		Vector<String> columnNames, Vector<String> classNames, Vector row,
		int keyCol
		)
	{
		super(tableName, columnNames, classNames, null, row, keyCol);
	}
	
	
	protected String getColumnsListWithoutKeyColumn()
	{
		StringBuffer cols = new StringBuffer(" ");
		
		int j = 0;
		boolean first = true;
		
		while (j < columnNames.size())
		{
			
			if (j != keyCol) // we assume that the key is autogenerated
			{
				if (first)
				{
					first = false;
				}
				else
				{
					cols.append(", ");
				}
				
				cols.append(columnNames.get(j));
			}
			j++;
		}
		
		return cols.toString();
	}
	
	protected String getValuesList()
	// build it lazily when we need (and have got) the real values
	{
		StringBuffer data = new StringBuffer(" VALUES (");
		int j = 0;
		boolean first = true;
		
		while (j < columnNames.size())
		{
			
			if (j != keyCol) // we assume that the key is autogenerated
			{
				if (first)
				{
					first = false;
				}
				else
				{
					data.append(", ");
				}
			
				boolean isStringValue = classNames.get(j).equals("java.lang.String"); 
				if (isStringValue) data.append("'");
				data.append("" + row.get(j));
				//System.out.println ( " value " + j + " value " + row.get(j));
				if (isStringValue) data.append("'");
			}
			j++;
		}
		data.append(")");
		return data.toString();
	}
	
	
	
	
	
	public String getSqlStatement()
	{
		String result = "insert into " + tableName +  " (" + getColumnsListWithoutKeyColumn() + ") " + getValuesList();
		System.out.println("TableInsertItem getSqlStatement() " + result);	
		return result;
	}
	
	
	
}
